name: flowcytometry
channels:
    - conda-forge
dependencies:
    - pandas
    - tqdm
    - pip
    - pip:
        - FlowCytometryTools
        - pprintpp
        - pydent
        - matplotlib==2.2.4
