name: flowcytometry
channels:
    - conda-forge
dependencies:
    - pandas==0.24.2
    - tqdm==4.23.4
    - pip==19.1.1
    - pip:
        - FlowCytometryTools==0.5.0
        - pprintpp==0.4.0
        - pydent==0.0.35
        - matplotlib==3.1.0
